// head.js
export default function Head() {
  return (
    <>
      <title>COMP1113 Calculator</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by David" />
      <link rel="icon" href="/img/bcit.ico" />
    </>
  );
}