// layout.js

import './globals.css'
import { Inter } from 'next/font/google'
import Header from "./header";
import Head from "./head";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'COMP1113 Calculator',
  description: 'Generated by cDavid',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head />
      <body> 
          <div className="flex flex-col">
              <Header />
              <main className="mt-4">{children}</main>
          </div>
      </body>
    </html>
  );
}
